### ISSUE TITLE
calling "memflowup install...." triggers a 'main' panicked at 'Must use...'

### ISSUE THREAD

**Issue by namar0x0309** [memflow/memflowup#6]
thread 'main' panicked at 'Must use `Arg::allow_invalid_utf8` with `_os` lookups at `[hash: 81FC9AF2D85DB0C5]`', /home/<username>/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.2.22/src/parser/matches/arg_matches.rs:1879:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by namar0x0309** [comment]
called `memflowup` directly in targets folder.
Solved by calling it through "cargo run <args>" in root of repo.

**Comment by ko1N** [comment]
I was finally able to repro it on my machine so we can have a detailled look into this. This is also related to https://github.com/clap-rs/clap/issues/3826

**Comment by ko1N** [comment]
Okay, switching to clap 4 solved this issue. The memflowup-init.sh script is also now updated to use 0.1.0-beta11. Hope this fixes the issue once and for all :)
