### ISSUE TITLE
When I run it prompts

### ISSUE THREAD

**Issue by gusqing** [memflow/memflowup#9]
gu@gu:~/a$ cargo run --release
warning: `/home/gu/.cargo/config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
warning: `/home/gu/.cargo/config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
error: could not find `Cargo.toml` in `/home/gu/a` or any parent directory
 

I'm sure I have installed the necessary requirements. Can you help me solve this problem? Thank you very much.

**Comment by ko1N** [comment]
What did you try to do? To install memflowup please follow the instructions from the readme:

The recommended way is to install it through our automated script:
```
curl --proto '=https' --tlsv1.2 -sSf https://sh.memflow.io | sh
```
Alternatively you can manually install it via cargo as well:
```
cargo install memflowup --force
```

Best,
ko1N
